# Generated by Django 2.1 on 2019-05-20 01:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_cadastro_broker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='ligacao_para',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='mensagem',
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='broker',
            field=models.CharField(default='', help_text='IP do servidor MQTT. Ex: 192.168.100.107', max_length=13, validators=[django.core.validators.validate_ipv4_address], verbose_name='Broker:'),
        ),
    ]
