# Generated by Django 2.1 on 2019-05-20 02:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20190519_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligacao_para', models.CharField(help_text='Número de destino. Ex: +5554988776655', max_length=14, validators=[django.core.validators.RegexValidator(code='erro_numero_destino', message='Formato de número inválido.', regex='^\\+[0-9]+$'), django.core.validators.MinLengthValidator(limit_value=14), django.core.validators.MaxLengthValidator(limit_value=14)], verbose_name='Destino:')),
                ('mensagem', models.CharField(help_text='Mensagem a ser enviada', max_length=500, verbose_name='Mensagem:')),
                ('cadastro', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cadastro.Cadastro')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
            },
        ),
    ]
